[package]
name = "openjd-python"
version = "0.9.0"
edition = "2021"

[lib]
name = "_openjd_rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
openjd-expr = { path = "../../openjd-rs/crates/openjd-expr" }
openjd-model = { path = "../../openjd-rs/crates/openjd-model" }
openjd-sessions = { path = "../../openjd-rs/crates/openjd-sessions" }
tokio = { version = "1", features = ["rt-multi-thread"] }
uuid = { version = "1", features = ["v4"] }
serde_yaml = "0.9"
serde_json = "1"
pyo3 = { version = "0.28", features = ["abi3-py39"] }
pyo3-log = "0.13"
log = "0.4"
pyo3-stub-gen = { version = "0.22", optional = true }

[[bin]]
name = "stub_gen"
required-features = ["stub-gen"]

[features]
default = []
extension-module = ["pyo3/extension-module"]
stub-gen = ["pyo3-stub-gen"]

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", features = [
    "Win32_Foundation",
] }
